# Nextest configuration
[profile.default]
# Run tests in parallel for speed
test-threads = "num-cpus"
# But limit heavy tests
slow-timeout = { period = "60s", terminate-after = 2 }

[profile.ci]
# More conservative for CI
test-threads = 4
slow-timeout = { period = "120s", terminate-after = 3 }
failure-output = "immediate-final"
fail-fast = false

# Retry flaky tests
[profile.default.retries]
count = 2

# Group simulation tests together
[[profile.default.overrides]]
filter = "test(simulation)"
test-threads = 1  # Simulation tests should run serially

# Model checking tests need more time
[[profile.default.overrides]]
filter = "test(model_check)"
slow-timeout = { period = "300s" }