[package]
name = "blixard"
version = "0.1.0"
edition = "2021"
authors = ["Blixard Contributors"]
description = "A distributed service management system built with Rust"
license = "MIT OR Apache-2.0"

[dependencies]
# CLI and argument parsing
clap = { version = "4.4", features = ["derive", "env"] }

# Async runtime
tokio = { version = "1.35", features = ["full"] }

# Distributed consensus (Raft)
tikv-raft = "0.14"
tikv-raft-proto = "0.14"

# Storage backend
redb = "1.5"

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bincode = "1.3"

# Logging and tracing
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# Error handling
anyhow = "1.0"
thiserror = "1.0"

# Networking
tonic = "0.10"
prost = "0.12"
tower = "0.4"

# Service discovery with Tailscale
reqwest = { version = "0.11", features = ["json"] }

# System interaction
sysinfo = "0.30"
nix = { version = "0.27", features = ["signal", "process"] }

# Utilities
uuid = { version = "1.6", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
dashmap = "5.5"
parking_lot = "0.12"
hostname = "0.3"

# Configuration
config = "0.13"
directories = "5.0"
toml = "0.8"

[build-dependencies]
tonic-build = "0.10"

[dev-dependencies]
tempfile = "3.8"
criterion = "0.5"
proptest = "1.4"

[[bench]]
name = "raft_benchmarks"
harness = false

[profile.release]
lto = true
codegen-units = 1
opt-level = 3

[profile.dev]
opt-level = 0
debug = true