[package]
name = "blixard"
version = "0.1.0"
edition = "2021"
rust-version = "1.75"
description = "Distributed microVM orchestration platform"
authors = ["Blixard Contributors"]

[dependencies]
# Consensus
raft = { version = "0.7", default-features = false, features = ["prost-codec"] }
raft-proto = { version = "0.7", default-features = false, features = ["prost-codec"] }

# Storage
redb = "2.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bincode = "1.3"

# Async runtime
tokio = { version = "1.35", features = ["full"] }
tokio-stream = { version = "0.1", features = ["time"] }
futures = "0.3"
async-trait = "0.1"

# CLI
clap = { version = "4.4", features = ["derive"] }
dialoguer = "0.11"

# Error handling
thiserror = "1.0"
anyhow = "1.0"
color-eyre = "0.6"

# Logging
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
slog = "2.7"

# Networking
tonic = "0.11"
prost = "0.12"
tower = "0.4"

# System interaction
nix = "0.27"
procfs = "0.16"
systemd = "0.10"

# Utilities
uuid = { version = "1.6", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
tempfile = "3.8"
bytes = "1.5"
rand = "0.8"
parking_lot = "0.12"
once_cell = "1.19"
scopeguard = "1.2"

# Deterministic simulation testing (optional)
madsim = { version = "0.2", optional = true }
fail = { version = "0.5", optional = true }

[dev-dependencies]
# Deterministic simulation and concurrency testing
turmoil = "0.6"
mock_instant = "0.3"
loom = { version = "0.7", features = ["checkpoint"] }
shuttle = "0.7"

# Property-based testing
proptest = "1.4"
test-case = "3.3"
rstest = "0.18"
quickcheck = "1.0"
arbitrary = { version = "1.3", features = ["derive"] }

# Fault injection
fail = { version = "0.5", features = ["failpoints"] }

# Model checking
stateright = "0.30"

# Test utilities
tempfile = "3.8"
criterion = "0.5"
pretty_assertions = "1.4"
insta = "1.34"
tracing-test = "0.2"
serial_test = "3.0"
assert_cmd = "2.0"
predicates = "3.0"

# Network simulation
pnet = "0.34"
pcap = "1.1"

[build-dependencies]
tonic-build = "0.11"

[features]
default = []
failpoints = ["fail/failpoints"]
simulation = ["madsim"]
all-tests = ["failpoints", "simulation"]

[[bin]]
name = "blixard"
path = "src/main.rs"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"

[profile.dev]
debug = true