[package]
name = "mvm"
version = "0.1.0"
edition = "2021"

[dependencies]
age = "0.10.0"
clap = { version = "4.5.4", features = ["derive"] }
dialoguer = "0.11.0"
openssl = "0.10.64"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
serde_yaml = "0.9.34"
