name = "blixard"
version = "1.0.0"

description = "A distributed service management system built with Gleam and Khepri"
licences = ["Apache-2.0"]

# Fill out repository and links if you want to publish to Hex
# repository = { type = "github", user = "username", repo = "blixard" }
# links = [{ title = "Website", href = "https://example.com/blixard" }]

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_erlang = ">= 0.34.0 and < 1.0.0"
gleam_otp = "~> 0.10 or ~> 1.0"
khepri = ">= 0.16.0 and < 1.0.0"
khepri_gleam = { git = "https://github.com/BrittonR/khepri_gleam.git", ref = "9f8fb371ec25" }
simplifile = ">= 1.7.0 and < 2.0.0"
gleam_community_ansi = ">= 1.4.3 and < 2.0.0"
shellout = ">= 1.7.0 and < 2.0.0"
ra = ">= 2.16.7 and < 3.0.0"
argv = ">= 1.0.2 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
