[alias]
# Convenience aliases for common test commands
test-all = "test --features test-helpers"
test-raft = "test --features test-helpers --test raft_state_machine_tests"
test-unit = "test --features test-helpers --lib"
test-integration = "test --features test-helpers --tests"

# Nextest aliases for improved test execution
nt = "nextest run"
nt-all = "nextest run --features test-helpers"
nt-raft = "nextest run --features test-helpers --test raft_state_machine_tests"
nt-unit = "nextest run --features test-helpers --lib"
nt-integration = "nextest run --features test-helpers --tests"
nt-ci = "nextest run --profile ci"
nt-stress = "nextest run --profile stress"
nt-retry = "nextest run --profile ci --no-fail-fast"
nt-verbose = "nextest run --no-capture"