[alias]
# Convenience aliases for common test commands
test-all = "test --features test-helpers"
test-raft = "test --features test-helpers --test raft_state_machine_tests"
test-unit = "test --features test-helpers --lib"
test-integration = "test --features test-helpers --tests"

# Nextest aliases for improved test execution
nt = "nextest run"
nt-all = "nextest run --features test-helpers"
nt-raft = "nextest run --features test-helpers --test raft_state_machine_tests"
nt-unit = "nextest run --features test-helpers --lib"
nt-integration = "nextest run --features test-helpers --tests"
nt-ci = "nextest run --profile ci --features test-helpers"
nt-stress = "nextest run --profile stress --features test-helpers"
nt-retry = "nextest run --profile ci --no-fail-fast --features test-helpers"
nt-verbose = "nextest run --no-capture --features test-helpers"

# MadSim test aliases (require: RUSTFLAGS="--cfg madsim" cargo nt-madsim)
nt-madsim = "nextest run --manifest-path simulation/Cargo.toml --test byzantine_tests --test clock_skew_tests"
nt-byzantine = "nextest run --manifest-path simulation/Cargo.toml --test byzantine_tests"
nt-clock-skew = "nextest run --manifest-path simulation/Cargo.toml --test clock_skew_tests"