[alias]
# Convenience aliases for common test commands
test-all = "test --features test-helpers"
test-raft = "test --features test-helpers --test raft_state_machine_tests"
test-unit = "test --features test-helpers --lib"
test-integration = "test --features test-helpers --tests"