# Blixard Security Configuration Example
# This file demonstrates all available security configuration options

[node]
bind_address = "127.0.0.1:7001"
data_dir = "./data"
vm_backend = "microvm"

[cluster]
bootstrap = false
join_address = "127.0.0.1:7001"

# Security Configuration
[security]

# TLS Configuration for encrypted communication
[security.tls]
# Enable TLS encryption for all gRPC communication
enabled = true

# Server certificate and key files
cert_file = "/etc/blixard/certs/server.crt"
key_file = "/etc/blixard/certs/server.key"

# CA certificate for client verification (optional)
ca_file = "/etc/blixard/certs/ca.crt"

# Require client certificates for mutual TLS authentication
# When true, clients must present valid certificates signed by the CA
require_client_cert = true

# Authentication Configuration
[security.auth]
# Enable authentication for API access
enabled = true

# Authentication method:
# - "token": Token-based authentication using API tokens
# - "mtls": Mutual TLS authentication using client certificates
method = "token"

# Token file containing pre-configured API tokens (optional)
# If not specified, tokens can be generated dynamically
token_file = "/etc/blixard/tokens/api-tokens.json"

# Example token file format:
# {
#   "sha256_hash_of_token": {
#     "token_hash": "sha256_hash_of_token",
#     "user": "admin-user",
#     "expires_at": null,
#     "permissions": ["Admin"],
#     "created_at": "2024-01-01T00:00:00Z",
#     "active": true
#   }
# }

# Additional configuration for completeness
[cluster.raft]
election_tick = 10
heartbeat_tick = 2

[observability.logging]
level = "info"
format = "pretty"

[observability.tracing]
enabled = true
service_name = "blixard-secure"

# Environment Variable Examples:
# The following environment variables can override these settings:
#
# TLS Configuration:
# export BLIXARD_TLS_ENABLED=true
# export BLIXARD_TLS_CERT_FILE=/path/to/cert.pem
# export BLIXARD_TLS_KEY_FILE=/path/to/key.pem
# export BLIXARD_TLS_CA_FILE=/path/to/ca.pem
# export BLIXARD_TLS_REQUIRE_CLIENT_CERT=true
#
# Authentication Configuration:
# export BLIXARD_AUTH_ENABLED=true
# export BLIXARD_AUTH_METHOD=token
# export BLIXARD_AUTH_TOKEN_FILE=/path/to/tokens.json