# Nextest configuration for Blixard

[profile.default]
# Enable experimental libtest-json for custom test harnesses
experimental = ["libtest-json"]
# Detect slow tests
slow-timeout = { period = "60s", terminate-after = 2 }

# Test groups for better organization
[[profile.default.overrides]]
filter = "test(raft_integration)"
threads-required = "num-cpus"
test-group = "integration-serial"

[test-groups]
# Force integration tests to run serially to avoid port conflicts
integration-serial = { max-threads = 1 }

# Retry flaky tests
[profile.ci]
retries = { backoff = "exponential", count = 2, delay = "1s" }
fail-fast = false

# Profile for local development - fail fast
[profile.dev]
fail-fast = true
failure-output = "immediate"
success-output = "never"
status-level = "skip"